### ISSUE TITLE
可以补个文件命名约定

### ISSUE THREAD

**Issue by netwjx** [doyoe/html-css-guide#1]
文档目录结构 部分约定了目录结构, 但是开发当中遇到最多的是找和当前html页面非通用部分有关的js css

对于sublime来说 可以按Ctrl+P输入一个名称就能快速定位文件, 如果对文件名有个约定将会对阅读和调试代码帮助很大

**Comment by doyoe** [comment]
酷，稍后补上

**Comment by doyoe** [comment]
done
